name: Build and Release apk

on:
  push:
    tags:
      - v*

jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Restore gradle.properties
        env:
          AMAP_KEY: ${{ secrets.AMAP_KEY }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "AMAP_KEY=${AMAP_KEY}" > ~/.gradle/gradle.properties
          echo "NESTOR_KEYSTORE_ALIAS=${KEY_ALIAS}" > ~/.gradle/gradle.properties
          echo "NESTOR_KEYSTORE_PASSWORD=${KEY_PASSWORD}" > ~/.gradle/gradle.properties
      - name: Build with Gradle
        run: chmod +x gradlew &&./gradlew aR
      - name: Release apk
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/release/*.apk"
          token: ${{ secrets.MY_GITHUB_ACCESSE }}
