name: Build and Release apk

on:
  push:
    tags:
      - v*

jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Gradle
        run: chmod +x gradlew &&./gradlew aR
        env:
          AMAP_KEY: ${{ secrets.AMAP_KEY }}
          NESTOR_KEYSTORE_ALIAS: ${{ secrets.KEY_ALIAS }}
          NESTOR_KEYSTORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Release apk
        uses: ncipollo/release-action@v1
        with:
          artifacts: "**/release/*.apk"
          token: ${{ secrets.MY_GITHUB_ACCESSE }}